export const UPDATE_CALORIES = 'UPDATE_CALORIES';
export const UPDATE_DAYS = 'UPDATE_DAYS';
export const UPDATE_PROTEINS = 'UPDATE_PROTEINS';
export const UPDATE_FATS = 'UPDATE_FATS';
export const UPDATE_CARBS = 'UPDATE_CARBS';
export const DELETE_MACRO = 'DELETE_MACRO';


// actions:
// CALORIES_PER_DAY
// DAYS_TO_MEALPLAN
// PROTEIN_PERCENTAGE
// CARBS_PERCENTAGE
// FATS_PERCENTAGE
// // food items
// ADD_ITEM
// DELETE_ITEM