export const UPDATE_MACRO = 'UPDATE_MACRO';

export const UPDATE_USERSETTING = 'UPDATE_USERSETTING';

// export const LOAD_USER = 'LOAD_USER';
export const USER_LOADED = 'USER_LOADED';
export const USER_UPDATED = 'USER_UPDATED';


// actions:
// CALORIES_PER_DAY
// DAYS_TO_MEALPLAN
// PROTEIN_PERCENTAGE
// CARBS_PERCENTAGE
// FATS_PERCENTAGE
// // food items
// ADD_ITEM
// DELETE_ITEM
