export const UPDATE_MACRO = 'UPDATE_MACRO';

export const UPDATE_USERSETTING = 'UPDATE_USERSETTING';



// actions:
// CALORIES_PER_DAY
// DAYS_TO_MEALPLAN
// PROTEIN_PERCENTAGE
// CARBS_PERCENTAGE
// FATS_PERCENTAGE
// // food items
// ADD_ITEM
// DELETE_ITEM
